source /etc/profile

for file in ~/.zsh/zsh.d/*; do
  source $file
done

# any settings specific to this machine
if [[ -f ~/.config/local/zshrc-local ]]; then
  source ~/.config/local/zshrc-local
fi

# FuzzyFinder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Syntax highlighting of CLI commands
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Fuzzyfinder defaults.
FZF_DEFAULT_OPTS='--height 40% --reverse'
FZF_CTRL_T_OPTS='--preview "head -n 100 {}" --preview-window right'
FZF_DEFAULT_COMMAND='ag --ignore *.pyc -g ""'
FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Use the base16 colorscheme
BASE16_SHELL=$HOME/.dotfiles/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
base16_tomorrow-night
