source /etc/profile

for file in ~/.zsh/zsh.d/*; do
  source $file
done

# any settings specific to this machine
if [[ -f ~/.zshrc-local ]]; then
  source ~/.zshrc-local
fi

# FuzzyFinder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
